In [3]:
import pandas as pd

# Read the Titanic dataset
df = pd.read_csv('titanic.csv')

# Total number of passengers in each class
total_first_class = df[df['Pclass'] == 1].shape[0]
total_second_class = df[df['Pclass'] == 2].shape[0]
total_third_class = df[df['Pclass'] == 3].shape[0]

# Filter the dataset for survivors in each class
survived_first_class = df[(df['Pclass'] == 1) & (df['Survived'] == 1)]
survived_second_class = df[(df['Pclass'] == 2) & (df['Survived'] == 1)]
survived_third_class = df[(df['Pclass'] == 3) & (df['Survived'] == 1)]

# Count the number of survivors in each class
num_survived_first_class = survived_first_class.shape[0]
num_survived_second_class = survived_second_class.shape[0]
num_survived_third_class = survived_third_class.shape[0]

# Calculate survival percentages
if total_first_class > 0:
    percent_survived_first_class = (num_survived_first_class / total_first_class) * 100
else:
    percent_survived_first_class = 0

if total_second_class > 0:
    percent_survived_second_class = (num_survived_second_class / total_second_class) * 100
else:
    percent_survived_second_class = 0

if total_third_class > 0:
    percent_survived_third_class = (num_survived_third_class / total_third_class) * 100
else:
    percent_survived_third_class = 0

# Display the counts, percentages, and details for each class
print(f"Number of 1st class survivors: {num_survived_first_class}")
print(f"Survival percentage for 1st class: {percent_survived_first_class:.2f}%")
print(survived_first_class[['Name', 'Pclass', 'Age', 'Fare']])
print()

print(f"Number of 2nd class survivors: {num_survived_second_class}")
print(f"Survival percentage for 2nd class: {percent_survived_second_class:.2f}%")
print(survived_second_class[['Name', 'Pclass', 'Age', 'Fare']])
print()

print(f"Number of 3rd class survivors: {num_survived_third_class}")
print(f"Survival percentage for 3rd class: {percent_survived_third_class:.2f}%")
print(survived_third_class[['Name', 'Pclass', 'Age', 'Fare']])

Number of 1st class survivors: 136
Survival percentage for 1st class: 62.96%
                                                  Name  Pclass   Age      Fare
1    Cumings, Mrs. John Bradley (Florence Briggs Th...       1  38.0   71.2833
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  35.0   53.1000
11                            Bonnell, Miss. Elizabeth       1  58.0   26.5500
23                        Sloper, Mr. William Thompson       1  28.0   35.5000
31      Spencer, Mrs. William Augustus (Marie Eugenie)       1   NaN  146.5208
..                                                 ...     ...   ...       ...
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...       1  48.0   25.9292
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)       1  47.0   52.5542
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)       1  56.0   83.1583
887                       Graham, Miss. Margaret Edith       1  19.0   30.0000
889                              Behr, Mr. Karl Howell       1  26.0   30.0000

[136 rows x 4 columns]

Number of 2nd class survivors: 87
Survival percentage for 2nd class: 47.28%
                                             Name  Pclass    Age     Fare
9             Nasser, Mrs. Nicholas (Adele Achem)       2  14.00  30.0708
15               Hewlett, Mrs. (Mary D Kingcome)        2  55.00  16.0000
17                   Williams, Mr. Charles Eugene       2    NaN  13.0000
21                          Beesley, Mr. Lawrence       2  34.00  13.0000
43       Laroche, Miss. Simonne Marie Anne Andree       2   3.00  41.5792
..                                            ...     ...    ...      ...
831               Richards, Master. George Sibley       2   0.83  18.7500
865                      Bystrom, Mrs. (Karolina)       2  42.00  13.0000
866                  Duran y More, Miss. Asuncion       2  27.00  13.8583
874         Abelson, Mrs. Samuel (Hannah Wizosky)       2  28.00  24.0000
880  Shelley, Mrs. William (Imanita Parrish Hall)       2  25.00  26.0000

[87 rows x 4 columns]

Number of 3rd class survivors: 119
Survival percentage for 3rd class: 24.24%
                                                  Name  Pclass   Age     Fare
2                               Heikkinen, Miss. Laina       3  26.0   7.9250
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       3  27.0  11.1333
10                     Sandstrom, Miss. Marguerite Rut       3   4.0  16.7000
19                             Masselmani, Mrs. Fatima       3   NaN   7.2250
22                         McGowan, Miss. Anna "Annie"       3  15.0   8.0292
..                                                 ...     ...   ...      ...
838                                    Chip, Mr. Chang       3  32.0  56.4958
855                         Aks, Mrs. Sam (Leah Rosen)       3  18.0   9.3500
858              Baclini, Mrs. Solomon (Latifa Qurban)       3  24.0  19.2583
869                    Johnson, Master. Harold Theodor       3   4.0  11.1333
875                   Najib, Miss. Adele Kiamie "Jane"       3  15.0   7.2250

[119 rows x 4 columns]